name: build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B -U verify --file pom.xml
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/jacoco-report/jacoco.xml
          retention-days: 1

  codecov:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download jacoco-report from build
        uses: actions/download-artifact@v2
        with:
          name: jacoco-report
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          files: jacoco.xml
